export enum Race {
  Goblin = "Goblin",
  CivilizedHuman = "CivilizedHuman",
  Barbarian = "Barbarian",
  AncientOrc = "AncientOrc",
  Orc = "Orc",
  HalfOrc = "HalfOrc",
  Elf = "Elf",
  DarkElf = "DarkElf",
  HalfElf = "HalfElf",
  HalfDarkElf = "HalfDarkElf",
  Dwarf = "Dwarf",
  Animal = "Animal",
  Bug = "Bug",
  Dragon = "Dragon",
  Mythical = "Mythical",
  CreatureOfDarkness = "CreatureOfDarkness",
  CreatureOfLight = "CreatureOfLight",
}