// <auto-generated />
using EntityFramework.MonsterBook;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFramework.MonsterBook.Migrations
{
    [DbContext(typeof(EfMonsterBookDbContext))]
    [Migration("20241008114039_StoringEnumAsStrings")]
    partial class StoringEnumAsStrings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.Armor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseArmorClass")
                        .HasColumnType("int");

                    b.Property<int>("BaseMovementInhibitoryFactor")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NameHu")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "NameHu")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL AND [NameHu] IS NOT NULL");

                    b.ToTable("Armor", (string)null);
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.AttackType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DamageType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("GuaranteedDamage")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfDices")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AttackType", (string)null);
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.CharacterArmor", b =>
                {
                    b.Property<int>("NpcTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("ArmorId")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalArmorClass")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalMovementInhibitoryFactor")
                        .HasColumnType("int");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("NpcTemplateId", "ArmorId");

                    b.HasIndex("ArmorId");

                    b.ToTable("CharacterArmor", (string)null);
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.CharacterFlaw", b =>
                {
                    b.Property<int>("NpcTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("FlawId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.HasKey("NpcTemplateId", "FlawId");

                    b.HasIndex("FlawId");

                    b.ToTable("CharacterFlaw", (string)null);
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.CharacterMerit", b =>
                {
                    b.Property<int>("NpcTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("MeritId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.HasKey("NpcTemplateId", "MeritId");

                    b.HasIndex("MeritId");

                    b.ToTable("CharacterMerit", (string)null);
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.CharacterSkill", b =>
                {
                    b.Property<int>("NpcTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("GuaranteedSuccesses")
                        .HasColumnType("int");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<int>("SkillLevelMax")
                        .HasColumnType("int");

                    b.Property<int>("SkillLevelMin")
                        .HasColumnType("int");

                    b.HasKey("NpcTemplateId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CharacterSkill", (string)null);
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.CharacterSkillCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstSecondary")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("NpcTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Primary")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("SecondSecondary")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Tertiary")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("NpcTemplateId")
                        .IsUnique();

                    b.ToTable("CharacterSkillCategories", (string)null);
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.CharacterWeapon", b =>
                {
                    b.Property<int>("NpcTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalAttackModifier")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalDefenseModifier")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalInitiativeModifier")
                        .HasColumnType("int");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("NpcTemplateId", "WeaponId");

                    b.HasIndex("WeaponId");

                    b.ToTable("CharacterWeapon", (string)null);
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.CharacterWeaponAttackType", b =>
                {
                    b.Property<int>("AttackTypeId")
                        .HasColumnType("int");

                    b.Property<int>("NpcTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("AttackTypeId", "NpcTemplateId", "WeaponId");

                    b.HasIndex("NpcTemplateId", "WeaponId");

                    b.ToTable("CharacterWeaponAttackType", (string)null);
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.Flaw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NameHu")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "NameHu")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL AND [NameHu] IS NOT NULL");

                    b.ToTable("Flaw", (string)null);
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.Merit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NameHu")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "NameHu")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL AND [NameHu] IS NOT NULL");

                    b.ToTable("Merit", (string)null);
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.NpcTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgilityMax")
                        .HasColumnType("int");

                    b.Property<int>("AgilityMin")
                        .HasColumnType("int");

                    b.Property<int>("BodyMax")
                        .HasColumnType("int");

                    b.Property<int>("BodyMin")
                        .HasColumnType("int");

                    b.Property<int>("DamageReductionMax")
                        .HasColumnType("int");

                    b.Property<int>("DamageReductionMin")
                        .HasColumnType("int");

                    b.Property<int>("DexterityMax")
                        .HasColumnType("int");

                    b.Property<int>("DexterityMin")
                        .HasColumnType("int");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("EmotionMax")
                        .HasColumnType("int");

                    b.Property<int>("EmotionMin")
                        .HasColumnType("int");

                    b.Property<int>("IntelligenceMax")
                        .HasColumnType("int");

                    b.Property<int>("IntelligenceMin")
                        .HasColumnType("int");

                    b.Property<int>("KarmaMax")
                        .HasColumnType("int");

                    b.Property<int>("KarmaMin")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameHu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("StrengthMax")
                        .HasColumnType("int");

                    b.Property<int>("StrengthMin")
                        .HasColumnType("int");

                    b.Property<int>("VitalityMax")
                        .HasColumnType("int");

                    b.Property<int>("VitalityMin")
                        .HasColumnType("int");

                    b.Property<int>("WillpowerMax")
                        .HasColumnType("int");

                    b.Property<int>("WillpowerMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NpcTemplate", (string)null);
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attribute1")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Attribute2")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NameHu")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "NameHu", "Category", "Attribute1", "Attribute2")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL AND [NameHu] IS NOT NULL");

                    b.ToTable("Skill", (string)null);
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseAttackModifier")
                        .HasColumnType("int");

                    b.Property<int>("BaseAttackTypeId")
                        .HasColumnType("int");

                    b.Property<int>("BaseDefenseModifier")
                        .HasColumnType("int");

                    b.Property<int>("BaseInitiativeModifier")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NameHu")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("BaseAttackTypeId");

                    b.HasIndex("Name", "NameHu")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL AND [NameHu] IS NOT NULL");

                    b.ToTable("Weapon", (string)null);
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.CharacterArmor", b =>
                {
                    b.HasOne("Mithrill.MonsterBook.Domain.Armor", "Armor")
                        .WithMany("CharacterArmors")
                        .HasForeignKey("ArmorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mithrill.MonsterBook.Domain.NpcTemplate", "NpcTemplate")
                        .WithMany("CreatureArmors")
                        .HasForeignKey("NpcTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Armor");

                    b.Navigation("NpcTemplate");
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.CharacterFlaw", b =>
                {
                    b.HasOne("Mithrill.MonsterBook.Domain.Flaw", "Flaw")
                        .WithMany("CreatureFlaws")
                        .HasForeignKey("FlawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mithrill.MonsterBook.Domain.NpcTemplate", "NpcTemplate")
                        .WithMany("CreatureFlaws")
                        .HasForeignKey("NpcTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flaw");

                    b.Navigation("NpcTemplate");
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.CharacterMerit", b =>
                {
                    b.HasOne("Mithrill.MonsterBook.Domain.Merit", "Merit")
                        .WithMany("CreatureMerits")
                        .HasForeignKey("MeritId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mithrill.MonsterBook.Domain.NpcTemplate", "NpcTemplate")
                        .WithMany("CreatureMerits")
                        .HasForeignKey("NpcTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merit");

                    b.Navigation("NpcTemplate");
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.CharacterSkill", b =>
                {
                    b.HasOne("Mithrill.MonsterBook.Domain.NpcTemplate", "NpcTemplate")
                        .WithMany("CreatureSkills")
                        .HasForeignKey("NpcTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mithrill.MonsterBook.Domain.Skill", "Skill")
                        .WithMany("CreatureSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpcTemplate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.CharacterSkillCategories", b =>
                {
                    b.HasOne("Mithrill.MonsterBook.Domain.NpcTemplate", "NpcTemplate")
                        .WithOne("CharacterSkillCategories")
                        .HasForeignKey("Mithrill.MonsterBook.Domain.CharacterSkillCategories", "NpcTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpcTemplate");
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.CharacterWeapon", b =>
                {
                    b.HasOne("Mithrill.MonsterBook.Domain.NpcTemplate", "NpcTemplate")
                        .WithMany("CreatureWeapons")
                        .HasForeignKey("NpcTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mithrill.MonsterBook.Domain.Weapon", "Weapon")
                        .WithMany("CreatureWeapons")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpcTemplate");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.CharacterWeaponAttackType", b =>
                {
                    b.HasOne("Mithrill.MonsterBook.Domain.AttackType", "AttackType")
                        .WithMany("CharacterWeaponAttackTypes")
                        .HasForeignKey("AttackTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mithrill.MonsterBook.Domain.CharacterWeapon", "CharacterWeapon")
                        .WithMany("AdditionalAttackTypes")
                        .HasForeignKey("NpcTemplateId", "WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttackType");

                    b.Navigation("CharacterWeapon");
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.Weapon", b =>
                {
                    b.HasOne("Mithrill.MonsterBook.Domain.AttackType", "BaseAttackType")
                        .WithMany("Weapons")
                        .HasForeignKey("BaseAttackTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaseAttackType");
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.Armor", b =>
                {
                    b.Navigation("CharacterArmors");
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.AttackType", b =>
                {
                    b.Navigation("CharacterWeaponAttackTypes");

                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.CharacterWeapon", b =>
                {
                    b.Navigation("AdditionalAttackTypes");
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.Flaw", b =>
                {
                    b.Navigation("CreatureFlaws");
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.Merit", b =>
                {
                    b.Navigation("CreatureMerits");
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.NpcTemplate", b =>
                {
                    b.Navigation("CharacterSkillCategories");

                    b.Navigation("CreatureArmors");

                    b.Navigation("CreatureFlaws");

                    b.Navigation("CreatureMerits");

                    b.Navigation("CreatureSkills");

                    b.Navigation("CreatureWeapons");
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.Skill", b =>
                {
                    b.Navigation("CreatureSkills");
                });

            modelBuilder.Entity("Mithrill.MonsterBook.Domain.Weapon", b =>
                {
                    b.Navigation("CreatureWeapons");
                });
#pragma warning restore 612, 618
        }
    }
}
